### ISSUE TITLE
USER STORY: Create "My Account" Page

### ISSUE THREAD

**Issue by GeorgeH23** [GeorgeH23/gym#8]
As a "registered gym member", I can "access and manage my user profile to edit personal data, update my password, and potentially delete my account" so that "I have control and flexibility over my account information, enhancing my user experience."

**Acceptance Criteria:**
- Create the My Account Page
- Allow user to edit/update/delete data
- Maintain Responsive Design

**Tasks:**
- [ ] Create and Design the Page
- [ ] User Data Actions (View, Edit, Update, Delete)
- [ ] Responsiveness
- [ ] Test and Review
